### ISSUE TITLE
background notification data

### ISSUE THREAD

**Issue by LazzaAU** [Fox520/pushyy#3]
When my device receives a background notification, in my 
```  
def my_notification_click_callback(self, data: RemoteMessage):
        print(f" Notification click callback initiated and data is => {data}")
```

The data is always empty. The message displays in the notification as expected but if you accidentally click the notification rather than expand the notification, the message disappears and the user never gets to see the actual message.

Therefore i'm wondering.... During background notification, when someone clicks the notification (not just expand it) how do i send the notifiication message to the app so i can also display it in the app ? 

assuming it has something to do with 

```
class RemoteMessage:

    notification: Notification = None # None when message originates from notification click
```
But i can't get my head around it 

cheers

**Comment by Fox520** [comment]
Hey! It appears to be [expected](https://firebase.google.com/docs/cloud-messaging/concept-options#notification-messages-with-optional-data-payload) behaviour.

> App behavior when receiving messages that include both notification and data payloads depends on whether the app is in the background or the foreground—essentially, whether or not it is active at the time of receipt.
>
> - **When in the background**, apps receive the notification payload in the notification tray, and only handle the data payload when the user taps on the notification.
> - **When in the foreground**, your app receives a message object with both payloads available.


A workaround is to include `title` & `body` in the `data` field and read from there instead of `notification`. e.g.
```jsonc
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "notification":{
      "title":"Portugal vs. Denmark",
      "body":"great match!"
    },
    "data" : {
      "title":"Portugal vs. Denmark", // <--- this
      "body":"great match!", // <--- this
      "Nick" : "Mario",
      "Room" : "PortugalVSDenmark"
    }
  }
}
```

---

Alternatively, when the app is in the background we could [store](https://github.com/Fox520/pushyy/blob/f880c024cc840dee0a03982b793b2793b9215066/src/python/libs/KivyFirebaseMessagingStore.java#L50-L53) the received notification using the message ID as an identifier. Later on when the notification is clicked, use the [message_id](https://github.com/Fox520/pushyy/blob/main/src/python/pushyy/remote_message.py#L18)  to [retrieve](https://github.com/Fox520/pushyy/blob/f880c024cc840dee0a03982b793b2793b9215066/src/python/libs/KivyFirebaseMessagingStore.java#L73) the notification from storage. That should include both `title` & `body`.

The retrieval could be done within the `if push_notification.get("notification") is None:` [condition](https://github.com/Fox520/pushyy/blob/main/src/python/pushyy/remote_message.py#L25)

**Comment by LazzaAU** [comment]
Ahhh, awesome. I understand what your saying. 

Thanks for the reply
